### PR TITLE
Compile ``nbody`` test from LFortran

### PR DESCRIPTION
**Pull request by czgdp1807**
`num = 1000000`

| Compiler | Time (s) | Relative |
|---|---|---|
| lc | 1.22 | 1.0 |
| clang++ -O3 -std=c++20 | 3.03  | 2.48 |
| clang++ -std=c++20 | >= 44.94 | >= 36.84 |

### CODE REVIEW

**Comment by czgdp1807** [comment]
Not ready for review yet.

**Comment by certik** [comment]
If you compile using:
```
clang++ -O3 -march=native -ffast-math nbody.cpp
```
Then I get 2.827s on Apple M1 Max.

**Comment by certik** [comment]
I also tried the fastest C++ version from here: https://gist.github.com/certik/c7803fe6cbf4f8a5ec3070dd699ecad3

And I get 
```console
$ clang++ -O3 -march=native -ffast-math a.cpp
$ time ./a.out 1000000                       
-0.169075164
-0.169086185
./a.out 1000000  0.04s user 0.00s system 92% cpu 0.046 total
```
So 3.6x faster than our LC version. Overall not bad I think as a start. We'll optimize things more in the future.

**Comment by czgdp1807** [comment]
Sure. I will work on these two examples next. There are excellent features which will be added through these two examples.

**Pull request merged**
