### PR TITLE
Use clang and clang++ for compilation in Ubuntu

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by certik** [comment]
I've seen this `PRIxPTR` error many times:
```
/home/runner/micromamba-root/envs/lc/include/llvm/Object/SymbolicFile.h:48:31: error: expected ')'
  OS << "(" << format("0x%08" PRIxPTR, D.p) << " (" << format("0x%08x", D.d.a)
```
I always forget what the issue is.

**Comment by czgdp1807** [comment]
LLVM seems broken on linux for this particular case. I am trying to workaround it. Since we don't need JIT functionality for now. We have more important things to do. Once we have a fix we can back to the original code without workarounds.

**Comment by czgdp1807** [comment]
Merging. Everything is unified across Ubuntu and macOS for LC. Whenever this LLVM issue is fixed we can switch back to `evaluator.cpp`.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
