### PR TITLE
Ported ``integration_tests/test_list_01.py`` from LPython and add support for ``std::vector`` in LC to compile it

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by certik** [comment]
Excellent! How is the performance on this one?

**Comment by czgdp1807** [comment]
Haven't checked yet. But ASR is the same so performance should be the same. Will check during the weekend.

**Comment by certik** [comment]
Performance will be the same as LPython, but I can't remember if we can beat Clang on this benchmark or not.

**Comment by czgdp1807** [comment]
```cpp
#include <vector>
#include <iostream>

int main() {
    std::vector<int32_t> v;
    for( int32_t i = 0; i < 400000000; i++ ) {
        v.push_back(i);
    }
    std::cout<<v[100000];
}
```

```zsh
(lc) 21:35:58:~/lc_project/lc % clang++ ../debug.cpp -std=c++17
(lc) 21:36:04:~/lc_project/lc % time ./a.out                   
100000./a.out  12.70s user 0.49s system 99% cpu 13.286 total
(lc) 21:36:18:~/lc_project/lc % lc ../debug.cpp -o a.out       
(lc) 21:37:17:~/lc_project/lc % time ./a.out                   
100000
./a.out  0.30s user 0.11s system 91% cpu 0.457 total
(lc) 21:37:20:~/lc_project/lc % clang++ ../debug.cpp -std=c++17 -O3
(lc) 21:37:30:~/lc_project/lc % time ./a.out                       
100000./a.out  0.25s user 0.26s system 91% cpu 0.560 total
```

`lc` NOFAST is 29.07x faster than `clang++` NOFAST (16.0.6) and 1.22x faster than `clang++ -O3`. I can't enable `lc --fast` via command line. I will add this option on Monday next week so that we can benchmark against `clang++` without issues.

**Comment by certik** [comment]
Great job. This is very promising. Let me review this carefully and double check everything.

**Pull request merged**
